?mutate
head()
temp<-mtcars
temp<-mutate(temp,temp$hp+temp$wt)
str(temp)
temp
View(temp)
unique(mtcars[c('cyl','gear')])
distinct(mtcars[c('cyl','gear')])
na+5
NA+5
NaN+5
group_by(mtcars,cyl)
?group_by
group_by(mtcars,cyl)
df1
df2
colnames(df2)<-c('age','child')
df2
df1
merge(df2,df1)
cbind(df2)<-c('x','y','z')
mtcars%>%arrange(cyl)%>%head(20)
mtcars%>%select(mpg,cyl,disp,hp,drat,gear,carb)%>%arrange(desc(gear))%>%filter(cyl==8)
temp<-mtcars
temp%>%mutate(new_col=wt/drat)%>%head(10)
summarise(mtcars,sd=sd(mpg),min=min(cyl),max=max(cyl),mean=mean(wt),med=median(drat))
sqldf('select * from mtcars')
